import 'package:sync_pro/config/enum.dart';

class TaskItemDisplayModel {
  final String title;
  final String customer;
  final String assignedTo;
  final TaskStatus status;
  final String description;
  final String assetId;
  final String assetName;
  final DateTime assignedAt;
  final DateTime? completedAt;
  final String address;
  final DateTime scheduledAt;
  final String priority;

  const TaskItemDisplayModel({
    required this.title,
    required this.customer,
    required this.assignedTo,
    required this.status,
    required this.description,
    required this.assetId,
    required this.assetName,
    required this.assignedAt,
    this.completedAt,
    required this.address,
    required this.scheduledAt,
    required this.priority,
  });
}

final List<TaskItemDisplayModel> mockTasks = [
  TaskItemDisplayModel(
    title: 'Air Conditioner Maintenance',
    customer: 'John Smith',
    assignedTo: 'Alice Johnson',
    status: TaskStatus.overdue,
    description: 'Inspect and clean the AC unit for efficient cooling.',
    assetId: 'A001',
    assetName: 'Daikin AC Unit',
    assignedAt: DateTime(2025, 10, 1, 9, 0),
    address: '123 Main Street, Yangon',
    scheduledAt: DateTime(2025, 10, 2, 10, 0),
    priority: 'High',
  ),
  TaskItemDisplayModel(
    title: 'Generator Oil Replacement',
    customer: 'Global Industries Ltd.',
    assignedTo: 'Bob Williams',
    status: TaskStatus.inProgress,
    description: 'Replace the generator oil and perform basic tests.',
    assetId: 'A002',
    assetName: 'Honda GX390 Generator',
    assignedAt: DateTime(2025, 10, 2, 8, 30),
    address: '456 Industrial Zone, Mandalay',
    scheduledAt: DateTime.now(),
    priority: 'Medium',
  ),
  TaskItemDisplayModel(
    title: 'Solar Panel Inspection',
    customer: 'Green Energy Co.',
    assignedTo: 'Charlie Kim',
    status: TaskStatus.completed,
    description: 'Check solar panel wiring and energy efficiency.',
    assetId: 'A003',
    assetName: 'SunPower 400W Panel',
    assignedAt: DateTime(2025, 9, 25, 9, 0),
    completedAt: DateTime(2025, 9, 25, 16, 0),
    address: '789 Energy Street, Naypyidaw',
    scheduledAt: DateTime(2025, 9, 26, 9, 0),
    priority: 'Low',
  ),
  TaskItemDisplayModel(
    title: 'Water Pump Repair',
    customer: 'AquaPure Ltd.',
    assignedTo: 'Alice Johnson',
    status: TaskStatus.notStarted,
    description: 'Diagnose and fix the broken pump motor.',
    assetId: 'A004',
    assetName: 'Grundfos Pump',
    assignedAt: DateTime(2025, 9, 5, 9, 0),
    address: '222 River Road, Yangon',
    scheduledAt: DateTime(2025, 10, 26, 9, 0),
    priority: 'High',
  ),
  TaskItemDisplayModel(
    title: 'Elevator Safety Check',
    customer: 'Sky Tower Apartments',
    assignedTo: 'Daniel Lee',
    status: TaskStatus.completed,
    description: 'Perform monthly safety and operation inspection.',
    assetId: 'A005',
    assetName: 'Otis Elevator',
    assignedAt: DateTime(2025, 9, 3, 8, 0),
    completedAt: DateTime(2025, 9, 4, 12, 0),
    address: '15 Tower Street, Yangon',
    scheduledAt: DateTime(2025, 9, 4, 9, 0),
    priority: 'Medium',
  ),
  TaskItemDisplayModel(
    title: 'Lighting System Upgrade',
    customer: 'City Mall Yangon',
    assignedTo: 'Emma Davis',
    status: TaskStatus.inProgress,
    description: 'Upgrade lighting system to LED for energy efficiency.',
    assetId: 'A006',
    assetName: 'Philips LED System',
    assignedAt: DateTime(2025, 10, 3, 8, 30),
    address: '88 Central Road, Yangon',
    scheduledAt: DateTime.now(),
    priority: 'High',
  ),
  TaskItemDisplayModel(
    title: 'Boiler Pressure Test',
    customer: 'Yangon Textile Co.',
    assignedTo: 'Charlie Kim',
    status: TaskStatus.overdue,
    description: 'Test boiler pressure and safety valves.',
    assetId: 'A007',
    assetName: 'Thermax Boiler',
    assignedAt: DateTime(2025, 9, 6, 9, 0),
    address: '77 Factory Zone, Yangon',
    scheduledAt: DateTime(2025, 9, 7, 8, 30),
    priority: 'High',
  ),
  TaskItemDisplayModel(
    title: 'HVAC Filter Replacement',
    customer: 'Shwe Hospital',
    assignedTo: 'Bob Williams',
    status: TaskStatus.notStarted,
    description: 'Replace all air filters and clean ducts.',
    assetId: 'A008',
    assetName: 'LG HVAC System',
    assignedAt: DateTime(2025, 9, 15, 9, 0),
    address: 'Health Road, Yangon',
    scheduledAt: DateTime(2025, 10, 16, 10, 0),
    priority: 'Medium',
  ),
  TaskItemDisplayModel(
    title: 'CCTV Maintenance',
    customer: 'SafeHome Security',
    assignedTo: 'Alice Johnson',
    status: TaskStatus.inProgress,
    description: 'Test and replace faulty cameras in the network.',
    assetId: 'A009',
    assetName: 'HikVision System',
    assignedAt: DateTime(2025, 9, 4, 9, 0),
    address: '90 Tech Street, Yangon',
    scheduledAt: DateTime.now(),
    priority: 'Low',
  ),
  TaskItemDisplayModel(
    title: 'Network Rack Installation',
    customer: 'FiberNet Ltd.',
    assignedTo: 'Daniel Lee',
    status: TaskStatus.completed,
    description: 'Install and configure new network racks.',
    assetId: 'A010',
    assetName: 'Cisco Rack System',
    assignedAt: DateTime(2025, 9, 10, 8, 0),
    completedAt: DateTime(2025, 10, 6, 17, 0),
    address: 'Internet Zone, Mandalay',
    scheduledAt: DateTime(2025, 10, 7, 10, 0),
    priority: 'High',
  ),
  TaskItemDisplayModel(
    title: 'UPS Battery Replacement',
    customer: 'DataTech Servers',
    assignedTo: 'Emma Davis',
    status: TaskStatus.overdue,
    description: 'Replace UPS batteries to prevent sudden shutdowns.',
    assetId: 'A011',
    assetName: 'APC Smart-UPS 5000VA',
    assignedAt: DateTime(2025, 9, 3, 9, 0),
    address: 'Digital Park, Yangon',
    scheduledAt: DateTime(2025, 9, 4, 11, 0),
    priority: 'Medium',
  ),
  TaskItemDisplayModel(
    title: 'Fire Alarm System Check',
    customer: 'Grand Hotel Yangon',
    assignedTo: 'Charlie Kim',
    status: TaskStatus.notStarted,
    description: 'Conduct safety checks and alarm response tests.',
    assetId: 'A012',
    assetName: 'Siemens Fire Alarm',
    assignedAt: DateTime(2025, 9, 28, 8, 30),
    address: 'Downtown Yangon',
    scheduledAt: DateTime(2025, 10, 29, 10, 0),
    priority: 'High',
  ),
];
